### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by limichange** [nuxt/example-auth0#1]
https://auth0.nuxtjs.org/

![image](https://cloud.githubusercontent.com/assets/1947344/22720032/69156b2a-ede3-11e6-9f8f-ff6085098490.png)

**Comment by Atinux** [comment]
This example will be online soon 👍

**Comment by limichange** [comment]
yeeeeee.

**Comment by Atinux** [comment]
😄

**Comment by mathiasconradt** [comment]
This issue should be re-opened, it still shows a 404 (again).
