### ISSUE TITLE
Unauthorized serving of secure content

### ISSUE THREAD

**Issue by simonlyn** [nuxt/example-auth0#11]
Hi,

Looking at the live demo, I'm able to fetch https://auth0.nuxtjs.org/_nuxt/4.nuxt.bundle.44ee0eecf0cba54387c9.js without having signed into Auth0
(I'm not sure if the actual URL will change but basically this file contains the content of secret page).

I've only just heard about Nuxt.js so I might be missing something, but it seems to me like you're only doing client-side authentication in this example? Is this by design? I would argue that this not secure at all.

Could you update the example to include how to protect the end-point (/_nuxt/4.nuxt.bundle.44ee0eecf0cba54387c9.js) against unauthorized requests?

I also had a look at https://nuxtjs.org/examples/auth-routes/. Unfortunately, it suffers from the same issues - I am able to fetch https://nuxt-auth-routes.glitch.me/_nuxt/1.nuxt.bundle.js without being authenticated.

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c12">#c12</a>)</em></sub></div>

**Comment by benmccallum** [comment]
Well this is kinda of worrying. Any comments from the nuxt team?!
