### ISSUE TITLE
[nuxt] state should be a function in store/index.js

### ISSUE THREAD

**Issue by yinshipeng** [nuxt/example-auth0#19]
![nuxt error](http://ow3sf64ph.bkt.clouddn.com/17-9-11/85289836.jpg)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c14">#c14</a>)</em></sub></div>

**Comment by promek** [comment]
Try changing the state variable in the store/index.js file as follows.

export const state = () => ({
   user: null
})

**Comment by IamManchanda** [comment]
@promek thanks ;)

**Comment by piiwa** [comment]
Solved, thks @promek 
Why is it happening ?

**Comment by klaveren** [comment]
Solved too, thank you.

**Comment by leoyli** [comment]
Hi, just wonder why the core team choosing to export state as a function rather than an object?  It seems counterintuitive since the state is indeed an object in vuex though...
