### ISSUE TITLE
Secure cookies

### ISSUE THREAD

**Issue by Atinux** [nuxt/example-auth0#2]
The cookie approach can be very safe if done properly. Doing the following is fairly trivial:

- use httpOnly flag (prevents JavaScript access to cookie)
- use secure flag (only set cookie for https requests)
- Signed cookies (verify source of cookie)

**Comment by hack2root** [comment]
I definetly can argue that all three that mentioned dirty tricks do not make any sense to authentication security

**Comment by Atinux** [comment]
What do you propose @hack2root ?

**Comment by maziarz** [comment]
@hack2root, how and why are these so called tricks categorized as dirty? You need to clarify things instead of leaving a cliffhanger.
