### ISSUE TITLE
Checked in `yarn.lock` file contains links to non-public repositories

### ISSUE THREAD

**Issue by mmieluch** [nuxt/example-auth0#20]
When trying to install dependencies with Yarn, the install command fails, because it cannot access some packages (the server returns _401 Unauthorized_.) As far as I'm aware the failing packages are:

- auth0-lock@10.15.1 resolving to ()[https://repository.neo9.pro/content/groups/global-npm/auth0-lock/-/auth0-lock-10.15.1.tgz#905f94b06a24150d9f1e12bb55f1667b205a8a31];
- idtoken-verifier@^1.0.1 resolving to ()[https://repository.neo9.pro/content/groups/global-npm/idtoken-verifier/-/idtoken-verifier-1.0.1.tgz#7563af238dfbc5aa2995744c37bf01dea3ad08ab]

As you can see, the URLs point to `https://repository.neo9.pro` instead of NPM or Yarn repositories.

Removing `yarn.lock` and installing sort of fixes the problem, but it defeats the purpose of having a lock file in the first place. I think @atinux was behind a proxy when he regenerated file in this commit: b40e16bf3a518a2eb5854efb2643c44b1eacfcd1

Easy to fix, submitting a PR.

**Comment by Atinux** [comment]
Nice catch @mmieluch
