### ISSUE TITLE
Auth0 Example is broken

### ISSUE THREAD

**Issue by limichange** [nuxt/example-auth0#22]
Auth0 Example is broken

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c7">#c7</a>)</em></sub></div>

**Comment by BruceHem** [comment]
Completely agreed, feels like it's abandoned.

**Comment by hmvella** [comment]
With a little gymnastics I was able to get it working by changing the following in the auth.js file:

- using $nuxt.$route.fullPath instead of window.location.href 
- wrapping anything else that used window in an if(process.browser).

**Comment by kriscamilleri** [comment]
With a little gymnastics I was able to get it working by changing the following in the auth.js file:

- using $nuxt.$route.fullPath instead of window.location.href
- wrapping anything else that used window in an if(process.browser).
