### ISSUE TITLE
These dependencies were not found:

### ISSUE THREAD

**Issue by haoxl3** [nuxt/example-auth0#23]
* ~/config.json in ./utils/lock.js
* ~components/ForkThis in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["E://private_projects//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./layouts/default.vue
* ~components/Navbar in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["E://private_projects//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./layouts/default.vue
* ~components/SuperSecretDiv in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":["E://private_projects//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./pages/index.vue

To install them, you can run: npm install --save ~/config.json ~components/ForkThis ~components/Navbar ~components/SuperSecretDiv

When I execute the command“npm install”"npm run dev",What happened？

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c6">#c6</a>)</em></sub></div>

**Comment by tld-uuid** [comment]
you 把  ~components 改成 ../components 试试

**Comment by cybibo** [comment]
I like this:


> npm install --save ~/config.json ~components/rkThis ~components/Navbar ~components/SuperSecretDiv
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../config.json" as it does not contain a package.json file.

**Comment by serzhikkk** [comment]
I have the same error. Please, fix this!

**Comment by BonnieDoug** [comment]
Also getting similar errors. As below:

```  ERROR  Failed to compile with 4 errors                                                                                                                                                                    12:22:05

These dependencies were not found:

* ~/config.json in ./utils/lock.js
* ~components/ForkThis in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/var/www/html/example-auth0/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
* ~components/Navbar in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/var/www/html/example-auth0/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
* ~components/SuperSecretDiv in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["/var/www/html/example-auth0/node_modules/babel-preset-vue-app/dist/index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue

To install them, you can run: npm install --save ~/config.json ~components/ForkThis ~components/Navbar ~components/SuperSecretDiv
```

Running the command as specified (To install them, you can run: npm install --save ~/config.json ~components/ForkThis ~components/Navbar ~components/SuperSecretDiv) simply results in another error:

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../../config.json" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-01-10T12_24_22_503Z-debug.log
```

**Comment by dzirtfox** [comment]
Same error

**Comment by dzirtfox** [comment]
Same error

* ~/config.json in ./utils/lock.js
* ~components/ForkThis in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["D://..//..//..//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
* ~components/Navbar in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["D://..//..//..//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./layouts/default.vue
* ~components/SuperSecretDiv in ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["D://..//..//..//example-auth0//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/index.vue

To install them, you can run: npm install --save ~/config.json ~components/ForkThis ~components/Navbar ~components/SuperSecretDiv

**Comment by claytopiccinin** [comment]
Same error here, any updates?

**Comment by warpedpuppy** [comment]
I solved this by adding a forward slash on those three dependencies.

So index.vue, line 21 went from:
import SuperSecretDiv from '~components/SuperSecretDiv'
to:
import SuperSecretDiv from '~/components/SuperSecretDiv'

And default.vue lines 12 & 13, from:
import Navbar from '~components/Navbar'
import ForkThis from '~components/ForkThis'
to:
import Navbar from '~/components/Navbar'
import ForkThis from '~/components/ForkThis'

**Comment by dbcbos** [comment]
Warpedpuppy has it right.

Adding forward slashes helps. You will need to also edit the store/index.js and replace the above three lines with this:

```
export const state = () => ({
  user: null
})
```

As was said in [](https://github.com/nuxt/example-auth0/issues/19)

Probably has to do with nuxt development improving and this was an old example. Needs a tiny update this git to get it to work
