### ISSUE TITLE
Future Problems with Disabled OIDC in Auth0

### ISSUE THREAD

**Issue by lanbau** [nuxt/example-auth0#24]
Hi, i wasn't able to run the example until i changed the following

- replaced ~components with ~/components
- changed state from object to a function

These helped to run the app. However, there was a persistent error when i tried to sign in with Auth0. All methods (Fb, username) responded with an error (token is not valid).

I managed to get the app working by disabling OIDC Conformant in my auth0 settings. 

Although it's working now, are there any experts that can point out if there are any potential problems in future?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c15">#c15</a>)</em></sub></div>

**Comment by dbcbos** [comment]
Hey thanx that helped me get the last piece of the puzzle. The app seems fully working now
