### ISSUE TITLE
id_token missing after login

### ISSUE THREAD

**Issue by vsimko** [nuxt/example-auth0#27]
related to this issue: https://github.com/auth0/lock/issues/809

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c16">#c16</a>)</em></sub></div>

**Comment by MattHoffmann** [comment]
Similar issue with id_token. I've configured passwordless authentication with the scope:

{
  "response_type": "token id_token",
  "scope": "openid"
}

and receive this error:

{
  "date": "2018-01-09T20:48:47.425Z",
  "type": "f",
  "description": "Missing required parameter: nonce",
  "connection": "email",
  "connection_id": "con_abc123",
  "client_id": "abc123",
  "ip": "123.123.123.123",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36",
  "details": {
    "body": {},
    "qs": {
      "scope": "openid",
      "response_type": "token id_token",
      "redirect_uri": "http://localhost:4200/callback",
      "verification_code": "123456",
      "connection": "email",
      "client_id": "XYZ",
      "email": "test@test.com"
    },
    "connection": "email",
    "error": {
      "message": "Missing required parameter: nonce",
      "oauthError": "invalid_request",
      "type": "request-error"
    }
  },
  "log_id": "49574419589858254662358705706112685939913750580601815074"
}

No matter what I do, I can't seem to get id_token to come back from passwordless authentication.

Thank You,

**Comment by vsimko** [comment]
have you tried this ?
```json
{
  "response_type": "token id_token",
  "scope": "openid",
  "nonce": "some random string"
}
```

**Comment by MattHoffmann** [comment]
I did try using a random string but then it told me that my nonce didn't match. I assume there is an ID generated on the server side that it needs to match.

**Comment by Musbell** [comment]
try adding the following like this:

> responseType: 'token id_token'
>  redirect: true
> scope: 'profile email'

```
 auth: {
      responseType: 'token id_token',
      redirect: true,
      params: {
        scope: 'profile email'
      }
    }
```
you can read this: [idToken coming back as undefined after upgrade #859](https://github.com/auth0/lock/issues/859)

**Comment by VikingTristan** [comment]
I guess my experience was a little different. I scratched my head for hours, it turns out I forgot that the Auth0 tutorial makes you create an email whitelist rule. I totally forgot about this. The rule made the idToken undefined in the response. Once I deleted the rule, this example worked perfectly.
