### ISSUE TITLE
CORS error occurs even though URL is set in Auth0 Dashboard

### ISSUE THREAD

**Issue by carlHandy** [nuxt/example-auth0#31]
Anybody knows how to fix this?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/example-auth0/issues/c19">#c19</a>)</em></sub></div>

**Comment by timhanlon** [comment]
Update auth0-lock to 11.3. If you've already done that, your issue could be Chrome's lack of support for Access-Control-Allow-Origin on localhost. To solve that, you can add a fake domain to your /etc/hosts or another workaround from here: https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin

**Comment by rorodouze** [comment]
We had the same problem. With version 11 of auth0-lock, the filed **Allowed Web Origins** in auth0 dashboard is now required. To pass from 10 to 11, just npm install the correct version and complete the fied.
This action doesn't appear yet in the readme of this repo.
