### ISSUE TITLE
~/config.json in ./utils/lock.js

### ISSUE THREAD

**Issue by SunXiao-Qi** [nuxt/example-auth0#34]
This dependency was not found:

* ~/config.json in ./utils/lock.js

请问怎么解决？

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/example-auth0/issues/c24">#c24</a>)</em></sub></div>

**Comment by francox9** [comment]
Rename config.sample.json to config.json
