### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by findingorder** [nuxt/example-auth0#38]
When I try to clone and 'npm run dev' this project, it seems to build and launch just fine. But when I navigate to localhost:3000, I get the error "ReferenceError: window is not defined". The offending line of code is server-bundle.js line 3538, "const json = window.localStorage.user;". Call stack is:

server-bundle.js:3538:16 getUserFromLocalStorage
server-bundle.js:2341:185
server-bundle.js:1630:15 promisify
server-bundle.js:1609:10 middlewareSeries
server-bundle.js:1125:72

**Comment by Syafiqq** [comment]
add mode:spa will fix the problem

nuxt.config.js
```
module.exports = {
  mode: 'spa',
	...
}
```

**Comment by iamanoctopus** [comment]
That works okay if you don't have any need for meta data for example. Since upgrading to latest on an oldish project, I've had an issue on `universal` getting it to run. It's a rabbit hole of errors after solving one thing to the next 😅

If anyone has any tips here, would appreciate it.

**Comment by yeahsmaggy** [comment]
@iamanoctopus  I'm having the same issue.
