### ISSUE TITLE
Can not open more than 2-3 tabs browser in dev mode

### ISSUE THREAD

**Issue by VienArchway** [nuxt/example-auth0#77]
### Version

[2.11.0](https://github.com/example-auth0/releases/tag/2.11.0)

### Reproduction link

[https://auth0.nuxtjs.org/](https://auth0.nuxtjs.org/)

### Steps to reproduce

Example-Auth0 (https://github.com/nuxt/example-auth0)

I had copied this example repos to local and register like README setup file.

![Screen Shot 2020-02-24 at 11.07.43.png](https://cmty.s3.eu-west-1.amazonaws.com/80991660/41a2b960-56c9-11ea-b354-51679b41c817.png)

I still have no idea yet. But I'll try to research config in dev mode

### What is expected ?

I want dev mode can open many tabs like pro mode

### What is actually happening?

In dev mode, can not open more than 3 tabs browsers

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/example-auth0/issues/c47">#c47</a>)</em></sub></div>

**Comment by a0972199950** [comment]
Same issue, but I cannot open more than two tabs in dev mode.
I use nuxt SSR, and when tabs are more than two, ajax request will be pending until one of the three tabs is closed =(

**Comment by Atinux** [comment]
This will be fixed with Nuxt V2.13
